name: Generate Release Notes

description: |
  Generates grouped release notes from conventional commits between two git tags.

inputs:
  older_tag:
    description: 'Older git tag (exclusive)'
    required: true
  latest_tag:
    description: 'Latest git tag (inclusive)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate release notes
      id: release_notes
      shell: bash
      run: |
        .github/actions/release_notes/generate_release_notes.sh "${{ inputs.older_tag }}" "${{ inputs.latest_tag }}"